# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cworker.proto\x12\x08trustann\"a\n\x0cQueryRequest\x12\x10\n\x08query_id\x18\x01 \x01(\t\x12\x0e\n\x06vector\x18\x02 \x03(\x02\x12\t\n\x01k\x18\x03 \x01(\r\x12\x10\n\x08shard_id\x18\x04 \x01(\r\x12\x12\n\nexperiment\x18\x05 \x01(\t\"(\n\x08Neighbor\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08\x64istance\x18\x02 \x01(\x02\"q\n\x08\x45vidence\x12\x12\n\ncommitment\x18\x01 \x01(\t\x12\x17\n\x0f\x63\x61ndidate_count\x18\x02 \x01(\r\x12\x13\n\x0b\x63onsistency\x18\x03 \x01(\x02\x12\x11\n\tdiversity\x18\x04 \x01(\x02\x12\x10\n\x08poisoned\x18\x05 \x01(\x08\"\xc9\x01\n\rQueryResponse\x12\x10\n\x08query_id\x18\x01 \x01(\t\x12\x10\n\x08shard_id\x18\x02 \x01(\r\x12\x12\n\nreplica_id\x18\x03 \x01(\r\x12\x11\n\tavailable\x18\x04 \x01(\x08\x12%\n\tneighbors\x18\x05 \x03(\x0b\x32\x12.trustann.Neighbor\x12$\n\x08\x65vidence\x18\x06 \x01(\x0b\x32\x12.trustann.Evidence\x12\r\n\x05\x65rror\x18\x07 \x01(\t\x12\x11\n\tserver_ms\x18\x08 \x01(\x01\"\x0f\n\rHealthRequest\"[\n\x0eHealthResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x10\n\x08shard_id\x18\x02 \x01(\r\x12\x12\n\nreplica_id\x18\x03 \x01(\r\x12\x17\n\x0findexed_vectors\x18\x04 \x01(\x04\x32\x80\x01\n\x06Worker\x12\x39\n\x06Search\x12\x16.trustann.QueryRequest\x1a\x17.trustann.QueryResponse\x12;\n\x06Health\x12\x17.trustann.HealthRequest\x1a\x18.trustann.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYREQUEST']._serialized_start=26
  _globals['_QUERYREQUEST']._serialized_end=123
  _globals['_NEIGHBOR']._serialized_start=125
  _globals['_NEIGHBOR']._serialized_end=165
  _globals['_EVIDENCE']._serialized_start=167
  _globals['_EVIDENCE']._serialized_end=280
  _globals['_QUERYRESPONSE']._serialized_start=283
  _globals['_QUERYRESPONSE']._serialized_end=484
  _globals['_HEALTHREQUEST']._serialized_start=486
  _globals['_HEALTHREQUEST']._serialized_end=501
  _globals['_HEALTHRESPONSE']._serialized_start=503
  _globals['_HEALTHRESPONSE']._serialized_end=594
  _globals['_WORKER']._serialized_start=597
  _globals['_WORKER']._serialized_end=725
# @@protoc_insertion_point(module_scope)
